[package]
name = "nf-installer"
version = "0.1.0"
edition = "2024"
authors = ["KarnesTH"]
license = "MIT"
description = "A CLI helper to install Nerd Fonts, Google Fonts and local font files"
repository = "https://github.com/KarnesTH/nf-installer"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.6", features = ["derive"] }
dirs = "6.0.0"
indicatif = "0.18.6"
inquire = "0.9.4"
reqwest = { version = "0.13.4", features = ["json"] }
scraper = "0.27.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
zip = "8.6.0"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
